### ISSUE TITLE
Can't run Katana

### ISSUE THREAD

**Issue by FaanMaario** [Hydreon/Katana#29]
Hi, I can't run Katana from source and I don't know how to compile it into .phar.

Can you help me?
Thanks for anwsering. :)

**Comment by mfmfneko** [comment]
@FaanMaario The usage is the same as the PocketMine-MP.

**Comment by diamond-gold** [comment]
I cant run it too, i got this error:
(running from src)

Fatal error: Uncaught exception 'RuntimeException' with message 'pthreads detected an attempt to connect to a Threaded which has already been destroyed' in C:\Users\user\Pocketmine servers\0.12.1\src\spl\BaseClassLoader.php:45
Stack trace:
#0 C:\Users\user\Pocketmine servers\0.12.1\src\spl\BaseClassLoader.php(45): BaseClassLoader::addPath()
#1 C:\Users\user\Pocketmine servers\0.12.1\src\pocketmine\PocketMine.php(109): BaseClassLoader->addPath('C:\\Users\\user...')
#2 {main}
  thrown in C:\Users\user\Pocketmine servers\0.12.1\src\spl\BaseClassLoader.php on line 45
bin\php\php.exe: Exit 255

**Comment by hlogeon** [comment]
@diamond-gold 
May be you have this problem because you use the newest version of SPL library. So, try to:
`cd src/spl` and then `git checkout d59c0f6`

**Comment by xxFlare** [comment]
@tntloverlol This is caused by them cloning the wrong raklib and spa files, not katana!

**Comment by PEMapModder** [comment]
Just `git submodule update --init --recursive` :)

**Comment by RandomAltThingy** [comment]
How do we compile this? We can compile pocketmine with devtools, but any changes somehow aren't saved when I do it.

**Comment by RandomAltThingy** [comment]
@tntloverlol Answer my question, then.

**Comment by tntloverlol** [comment]
@RandomAltThingy You can't compile PHP, it's a scripting language. This repository is intended for PocketMine's power users who want more performance from the software. Please acquire a baseline level of knowledge about the command line, git, and computers in general, before asking questions and disturbing this repository's peace. Thank you :)
