### ISSUE TITLE
Startup errors (w/ steps to reproduce)

### ISSUE THREAD

**Issue by RandomAltThingy** [Hydreon/Katana#34]
Sometimes on startup it gives an error.

**Steps to reproduce:**
*Note: There may be more*

1. Compile the katana phar with devtools. And run it with ./start.sh
2. Edit the katana.yml by setting transfer to true and editing the target server IP. I changed it to play.thecloudpvp.net.
3. Then run /stop on the server
4. Run ./start.sh

For me it gave an error on null.

**Comment by RandomAltThingy** [comment]
To fix, I just recopied the compiled phar that we initially created using Devtools and overrited the one that gave the error.

**Comment by PEMapModder** [comment]
Then that means you compiled it incorrectly...

**Comment by RandomAltThingy** [comment]
Nope, I followed the video by @KnownUnown.

**Comment by PEMapModder** [comment]
So a file generated in the same way can result in two different results?
