### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by patrickt1220** [Hydreon/Katana#35]
I put all the files in the directory and when I do /start.sh Linux is telling me Permission Denied.  No big deal I just have to change the permissions.... Well I then did Chown -R PocketMine /home/PocketMine/ and It still didn't work so Im confused to what Im doing wrong.

**Comment by williamtdr** [comment]
chmod +rx start.sh; ./start.sh

**Comment by patrickt1220** [comment]
Thanks you :+1:
