### ISSUE TITLE
Crash Dump Saving

### ISSUE THREAD

**Issue by RandomAltThingy** [Hydreon/Katana#37]
So, when crash dump saving is enabled, why not save it inside its own folder? Since large minigames server will likely have crashes when testing new plugins, you may as well organise it. This is also useful if you want crash dumps enabled but then you want to go to edit the server properties - but that's at the end of the folder with tons of crash dumps in front.

@shoghicp

**Comment by PEMapModder** [comment]
I think this change should be done at PocketMine instead. This is not specific to "large minigames server".
