### ISSUE TITLE
Option to save player data to SQLite database, or MySQL.

### ISSUE THREAD

**Issue by RandomAltThingy** [Hydreon/Katana#39]
This wouldnt be too hard to implement. This would be useful because sometimes saving player data is needed, but it takes up too much space and apparently takes time to write to the disk. Saving it in a database can free up storage space and (I'm assuming) make the saving of the data quicker.

**Comment by xxFlare** [comment]
I'm afraid you do not understand the point of Katana.

Katana is made to reduce PocketMines heavy resource usage, free up disk I/O and improve core performance. Katana is not made to add extra features.

Now.. there are two problems with your request.
1. This feature is not useful to us and querying is the least thing we want to do.
2. This can be done plugin-side.
3. This is not a feature tab! Please keep it related to issues.

Thanks.

**Comment by RandomAltThingy** [comment]
That's funny, when there is a label specifically for "Feature request".
Please read my previous issue.

**Comment by PEMapModder** [comment]
"Katana is designed for our intended use." "Katana is not for everyone's use."
