### ISSUE TITLE
Error starting server while redirect option is true

### ISSUE THREAD

**Issue by vvzar** [Hydreon/Katana#43]
,_._._._._._._._._|______________________________________________
___,
|_|_|_|_|_|_|_|_|_|______________________________________________
__/
     _            l
    | | ____ _| |_ __ _ _ __   __ _
    | |/ / _` | __/ _` | '_ \ / _` |    MCPE v0.12.1 alpha
    |   < (_| | || (_| | | | | (_| |    Katana 1.6dev
    |_|\_\__,_|\__\__,_|_| |_|\__,_|
 
Katana is a fork of PocketMine-MP, distributed under the LGPL lic
ence
 
Fatal error: Call to a member function katana() on null in phar:/
//mcpe/shared/servers/Katana_1.6dev.phar/src/pocketmine/katana/Ka
tanaModule.php on line 50
stop

**Comment by RandomAltThingy** [comment]
Finally!
