### ISSUE TITLE
Is pocketmine.yml used by katana?

### ISSUE THREAD

**Issue by vvzar** [Hydreon/Katana#52]
I saw freezes by memory exhosted reason. So I need increase memory limits but I dont know how.

**Comment by PEMapModder** [comment]
Yes. Both yml files.

**Comment by vvzar** [comment]
Where can I increase limit of ram in this case:
Main thread setting to 0 and second limit to 0 - 
doesnt help.

Fatal error: Allowed memory size of 134217728 bytes exhausted (tr
ied to allocate 8208 bytes) in phar:///mcpe/shared/servers/Katana
_1.6dev.phar/src/raklib/server/RakLibServer.php on line 128

**Comment by PEMapModder** [comment]
Why did you set the RAM limit to 0...

**Comment by vvzar** [comment]
for experimental purposes :).

My servers periodically freeze with:

Fatal error: Allowed memory size of 134217728 bytes exhausted (tr
ied to allocate 8208 bytes) in phar:///mcpe/shared/servers/Katana
_1.6dev.phar/src/raklib/server/RakLibServer.php on line 128

and I dont know how fix this...

The are all restarting every 30 minutes or near it. But it is not helpful.

**Comment by xxFlare** [comment]
If you are experimenting..Why is this a problem?

Setting RAM limit to 0 will obviously kill the server because you are not allowing it resources to run.

**Comment by PEMapModder** [comment]
Can you set `debug.level` in pocketmine.yml to 2 and do /status and /dumpmemory when you feel that the server is about to crash?

**Comment by vvzar** [comment]
I do this right now, Thank You.

**Comment by vvzar** [comment]
xxFlare, I experimenting after this freeze already happened. Usually my memory limits are: global 512 - 2048, and main 320 - 1024
